### PR TITLE
Converted ipynb files to py files to extract dependency - Issue #3

### PR DESCRIPTION
**Pull request by Aftabby**
The code now checks for files ending with the `.ipynb` extension along with the original extension specified.

Implemented `.ipynb` to `.py` conversion. A new function `convert_ipynb_to_py()` is included. This function uses the `nbformat` library (which has been included) to read the code cells from the `.ipynb` file and write them to a newly created `.py` file.

The converted `.py` file is added to the list of files to be processed for requirement extraction.

[] Closes Issue #3

### CODE REVIEW

**Comment by wilderlopes** [comment]
Hi @Aftabby , thanks for the contribution. I found a few problems while testing the PR in this repo that contains a ipynb file: https://github.com/Ogarantia/tensorflow-attention.git

1. The ipynb there has an iPython command whose syntax is illegal in Python scripts: `!pip install "tensorflow-text==2.8.*"`. This line also appears in the converted file and miniogre can't really pull the imports. Another iPython-only command that should be removed is `%% time`.
2. The created files (.py) should be removed after the generation of the requirements. This is because these files didn't exist in the original repo, and we shouldn't pollute it by duplicating the contents of the file (only the .ipynb should be kept).

I didn't dig into it too much, but there might be a few ideas here: https://nbconvert.readthedocs.io/en/latest/nbconvert_library.html 

Or even maybe use `subprocess` to call `nbconvert`? See this: https://nbconvert.readthedocs.io/en/latest/usage.html

**Comment by wilderlopes** [comment]
@Aftabby -- any updates? Let us know if you need help.

**Comment by Aftabby** [comment]
@wilderlopes Thank you for checking up on that, I am quite unsure how to handle the unique expression like your mentioned ones ` !pip install "tensorflow-text==2.8.*"` .
Needless to say, I am still at beginner level. So, yes if you could provide some hints that might help me track down the solution.

Thank you for understanding.

**Comment by wilderlopes** [comment]
Hi @Aftabby. After checking your pull request, I noticed there were some issues that needed fixing. In the process of fixing it, I realized it was better to try a totally new approach, which have been pushed to main (https://github.com/ogre-run/miniogre/commit/88067d9a4bd17a4ba51e99c0cff6d921cc2677a6).

Thus, I am closing this pull request because this solution won't be implemented.

**Pull request closed without merging**
